### ISSUE TITLE
Could you please provide the keras implement？

### ISSUE THREAD

**Issue by Ianwtg** [alexandrosstergiou/SoftPool#21]
Hi， thank you for your great work. 
Could you please provide the keras implement？

**Comment by alexandrosstergiou** [comment]
Hi @Ianwtg ,

We have not created a Keras/TensorFlow implementation for the project. You could however implement it with Keras/TensorFlow build-in functions similar to the PyTorch CPU version [seen in lines 207-210](https://github.com/alexandrosstergiou/SoftPool/blob/041b2ce331a15e1b942e1181044c6d2b36408d25/pytorch/SoftPool/idea.py#L207-L210).

Best,
Alex
