### ISSUE TITLE
about padding

### ISSUE THREAD

**Issue by 123wk45678** [alexandrosstergiou/SoftPool#25]
i want to add a parameter about "padding",i wonder if it is oK to do that ?

**Comment by alexandrosstergiou** [comment]
Hi @123wk45678 ,

You can refer to the previous two issues that were about padding [#25](https://github.com/alexandrosstergiou/SoftPool/issues/22) and [#15](https://github.com/alexandrosstergiou/SoftPool/issues/15)

Best,
Alex
