### ISSUE TITLE
provide ImageNet weight architecture

### ISSUE THREAD

**Issue by Yee-Master** [alexandrosstergiou/SoftPool#28]
provide ImageNet weight only change maxpool to softpool?

have any differnet from torchvision.models?

**Comment by alexandrosstergiou** [comment]
Hi @Yee-Master ,

The project corresponds to this paper [2101.00440](https://arxiv.org/abs/2101.00440). The downsampling method is tested on the basis of similarity to the original input and possible improvements by pooling layer replacements for image and video recognition.

Best,
Alex
