### ISSUE TITLE
识别精度

### ISSUE THREAD

**Issue by Weiziwei521** [alexandrosstergiou/SoftPool#33]
在图像识别任务上，把最后分类池化层换为softpool时，识别精度由之前的90%降低到几乎为0，这有可能是什么原因造成的呢？

**Comment by MoonGhost96** [comment]
你重新训练了吗，最近的bug修复了cuda版本的stride问题，cpu版本我试了，好像是有bug

**Comment by alexandrosstergiou** [comment]
Not sure what "final classification layer" refers to (or if Google Translate does not do your question justice). If it refers to using SoftPool for vectorization, we do not perform any experiments for this. 

In the odd case that you're using a GPU-trained model within a CPU environment, you are probably using two different implementations. You can find the differences (and reasons for their differences) in implementations from this comment in issue [#31](https://github.com/alexandrosstergiou/SoftPool/issues/31#issuecomment-811742176).

I will be closing this issue for now, but if you have a more specific question - or some clarification, you can either open it again or create a new issue. Preferably in English, so no one gets lost in translation.
