### ISSUE TITLE
Hello, I find a bug when i use softpool2d.

### ISSUE THREAD

**Issue by AAAAAA128** [alexandrosstergiou/SoftPool#36]
RuntimeError: input.is_contiguous() INTERNAL ASSERT FAILED at "/export/w/SoftPool/pytorch/CUDA/softpool_cuda.cpp":120, please report a bug to PyTorch. input must be a contiguous tensor

**Comment by alexandrosstergiou** [comment]
Hi @KeqiWangSXuniversity,

This question has been answered in previous issues #6  and #16.

It just means that the tensor that you're passing as an argument does not occupy a contiguous memory space. You can use `.contiguous()` alongside the function call, although most recent repo versions do internal checks.

Best,
Alex
