### ISSUE TITLE
There was an error when I used softpool on the AlexNet during classification task training.

### ISSUE THREAD

**Issue by JonasZero** [alexandrosstergiou/SoftPool#38]
File "/home/csu/anaconda3/envs/wsy/lib/python3.6/site-packages/SoftPool-1.1-py3.6-linux-x86_64.egg/SoftPool/idea.py", line 192, in soft_pool2d
    if torch.isnan(x).any():
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

The changes in my model are as follows：
def __init__(self, num_classes: int = 1000) -> None:     
    super(AlexNet, self).__init__()
    self.conv1 = nn.Sequential(
        ......
    )

    self.conv2 = nn.Sequential(
        nn.Conv2d(64, 192, kernel_size=5, padding=2),
        nn.ReLU(inplace=True),
        SoftPool2d(kernel_size=3, stride=2), # This is where I changed
    )

When I replace the softpool of the self.conv1 structure, no error occurs at runtime. However, an error occurred while replacing the self.conv2 structure.
The GPU I use is RTX 3090. The version of pytorch I use is 1.9.0.

**Comment by alexandrosstergiou** [comment]
Hi @JonasZero,

Usually, an illegal memory access error would be associated with indexing (i.e trying to access a tensor location that does not exist ). What is your input size when applying SoftPool? Have you made sure that this size can indeed be used with `kerenl_size=3` and `stride=2`?

Best,
Alex

**Comment by JonasZero** [comment]
> Hi @JonasZero,
> 
> Usually, an illegal memory access error would be associated with indexing (i.e trying to access a tensor location that does not exist ). What is your input size when applying SoftPool? Have you made sure that this size can indeed be used with `kerenl_size=3` and `stride=2`?
> 
> Best,
> Alex

Thank you for your reply. The original is “nn.MaxPool2d(kernel_size=3, stride=2)”, I replaced it with "SoftPool2d(kernel_size=3, stride=2)". This is really a strange problem. I have no problem replacing other pooling layers.

**Comment by alexandrosstergiou** [comment]
You need to ensure that the size of your input is compatible with the kernel and stride sizes that you have used (i.e. 3, 2). The formula is quite simple to figure out: `W - K (+2P) / S`, where `W`: the width or the height dimension, `K`: is the kernel size, `P` is padding, and `S` is the stride. If you are getting a non-integer number you should change the input size.

**Comment by JonasZero** [comment]
> You need to ensure that the size of your input is compatible with the kernel and stride sizes that you have used (i.e. 3, 2). The formula is quite simple to figure out: `W - K (+2P) / S`, where `W`: the width or the height dimension, `K`: is the kernel size, `P` is padding, and `S` is the stride. If you are getting a non-integer number you should change the input size.

Thank you. I'll check it carefully.

**Comment by JonasZero** [comment]
> You need to ensure that the size of your input is compatible with the kernel and stride sizes that you have used (i.e. 3, 2). The formula is quite simple to figure out: `W - K (+2P) / S`, where `W`: the width or the height dimension, `K`: is the kernel size, `P` is padding, and `S` is the stride. If you are getting a non-integer number you should change the input size.

I set the following parameters to solve the problem: 
'force_inplace=True'
