### ISSUE TITLE
There is a problem with the installation

### ISSUE THREAD

**Issue by Adong-1209** [alexandrosstergiou/SoftPool#39]
I am a rookie. I have the following installation problems when using Windows system
![1](https://user-images.githubusercontent.com/90688177/133235741-231ad1e5-92b1-4ae9-bd47-01a270846308.PNG)

**Comment by alexandrosstergiou** [comment]
Hi @Adong-1209 ,

From a quick search [[link]](https://github.com/sammchardy/python-binance/issues/148), your problem is related to Microsoft Visual C++. Apart from following the solutions from the issue that I sent you, you can also either:
- install a Linux distro and try installing the project there.
**or**
- use the CPU version of the code without installing the CUDA implementation.

**Comment by Adong-1209** [comment]
> Hi @Adong-1209 ,
> 
> From a quick search [[link]](https://github.com/sammchardy/python-binance/issues/148), your problem is related to Microsoft Visual C++. Apart from following the solutions from the issue that I sent you, you can also either:
> 
> * install a Linux distro and try installing the project there.
>   **or**
> * use the CPU version of the code without installing the CUDA implementation.

I tried most of the methods in that link, but I still couldn't solve the problem. What a pity. Even so, thank you for your help.

**Comment by Adong-1209** [comment]
> > Hi @Adong-1209 ,
> > From a quick search [[link]](https://github.com/sammchardy/python-binance/issues/148), your problem is related to Microsoft Visual C++. Apart from following the solutions from the issue that I sent you, you can also either:
> > 
> > * install a Linux distro and try installing the project there.
> >   **or**
> > * use the CPU version of the code without installing the CUDA implementation.
> 
> I tried most of the methods in that link, but I still couldn't solve the problem. What a pity. Even so, thank you for your help.

I tried for the last time, and this time it worked. I don't know what happened, maybe because I created a new environment or a project interpreter.

**Comment by alexandrosstergiou** [comment]
The CUDA implementation is essentially an extension (so it needs to be compiled to run alongside PyTorch). By using the python PyTorch-native code, you can run it in both your CPU and GPU(s) with the only trade-off that it will be slower than the CUDA. 

So the installation is only if you want to use the CUDA implementation. You can still use the repo without installing it.

Hope the above helped!

**Comment by Adong-1209** [comment]
> The CUDA implementation is essentially an extension (so it needs to be compiled to run alongside PyTorch). By using the python PyTorch-native code, you can run it in both your CPU and GPU(s) with the only trade-off that it will be slower than the CUDA.
> 
> So the installation is only if you want to use the CUDA implementation. You can still use the repo without installing it.
> 
> Hope the above helped!

Yes, I do need to use CUDA

**Comment by alexandrosstergiou** [comment]
> > The CUDA implementation is essentially an extension (so it needs to be compiled to run alongside PyTorch). By using the python PyTorch-native code, you can run it in both your CPU and GPU(s) with the only trade-off that it will be slower than the CUDA.
> > So the installation is only if you want to use the CUDA implementation. You can still use the repo without installing it.
> > Hope the above helped!
> 
> Yes, I do need to use CUDA

You can then either: 1) use the PyTorch-native code of the repo without installing it **OR**  2) try to resolve the compiler error.

Will be closing this issue for now since the simplest solution is to not install the repo and use the pytorch-native implementation. Feel free to open a new issue if other problems occur.

Best,
Alex
