### ISSUE TITLE
A problem I encountered when I was training

### ISSUE THREAD

**Issue by Adong-1209** [alexandrosstergiou/SoftPool#40]
![捕获](https://user-images.githubusercontent.com/90688177/134306213-9a2922c4-9ab7-4b8a-9427-49d0906901b2.PNG)

**Comment by alexandrosstergiou** [comment]
Hi @Adong-1209,

Are you using the latest pytorch version? Based on [this](https://discuss.pytorch.org/t/cuda-error-an-illegal-instruction-was-encountered/88326) post your error could be related to the pytorch version used to run your code.

You can also use the ```force_inplace``` flag alternatively, if you want a quick fix.

**Comment by alexandrosstergiou** [comment]
Closing for now but feel free to re-open a new issue if there are any other problems.
