### ISSUE TITLE
A problem of install error

### ISSUE THREAD

**Issue by Chaolu1997** [alexandrosstergiou/SoftPool#41]
(base) cx@amax:~/CL/HashNet-master/SoftPool-master/pytorch$ make install
rm -rf *.egg-info
rm -rf build dist
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
-----------------------------------------------
what's matter with that ?

**Comment by alexandrosstergiou** [comment]
Hi @Chaolu1997,

As the error says, you will need to have pytorch installed first before you attempt to build the repo.
