### ISSUE TITLE
softpool_cuda issue !

### ISSUE THREAD

**Issue by ahmedeqbal** [alexandrosstergiou/SoftPool#46]
Hello,

i was remain unsuccessful to install via following commonds:

```
$ git clone https://github.com/alexandrosstergiou/SoftPool.git
$ cd SoftPool-master/pytorch
$ make install
```

So, i have created and directly call **SoftPool.py** file. and it works fine. However, by commenting `softpool_cuda.forward_2d(input.contiguous(), kernel, stride, output)`

Because this library not properly installed, so i am unable to "**import softpool_cuda**", is there any trick to directly call these CUDA, and .cpp files in Python import? So, i can make **softpool_cuda** function work?

Waiting for reply...

**Comment by alexandrosstergiou** [comment]
Hi @ahmedeqbal ,

You can use the pythonic implementation of softpool with `force_inplace=True` when calling a function or creating a class object (and removing the import statements/code to the CUDA and C++ wrapper(s)). Alternatively, you can have a look at [this pytorch post](https://pytorch.org/tutorials/advanced/cpp_extension.html) and tailor the code accordingly.
