### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by icvplayer** [alexandrosstergiou/SoftPool#50]
Hi, If I set force_inplace to False, CUDA will report an error: 
RuntimeError: CUDA error: an illegal memory access was encountered.
cudaCheckError() failed : an illegal memory access was encountered. 
Could you tell me why please?

**Comment by alexandrosstergiou** [comment]
Hi @icvplayer ,

This is likely due to your tensor not being contiguous in memory (of the gradients of it). You can wrap the function call around `contiguous()` calls.
