### ISSUE TITLE
about kernel_size problem

### ISSUE THREAD

**Issue by moshicaixi** [alexandrosstergiou/SoftPool#53]
For 2d-pool, the kernel height and kernel width must be equal? Can i use the kernel like (1,2) shape? Thx for your help!

![image](https://user-images.githubusercontent.com/63298919/192225708-2f8e028b-7e28-4efc-8291-b5ce134cf6e2.png)

**Comment by alexandrosstergiou** [comment]
Hi @moshicaixi ,

The current implementation does require equal kernel height/width. However, I have not tried to remove the constraint and use uneven sizes. If you do decide to test it and it does work, do let me know.

**Comment by alexandrosstergiou** [comment]
I'll close the issue for now but feel free to post updates.
