### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by raozhongyu** [alexandrosstergiou/SoftPool#54]
Thanks for your brilliant work!
After i run make install, i got this
ImportError: /home/envs/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: invalid ELF header.
How can i solve this.

**Comment by alexandrosstergiou** [comment]
Hi @raozhongyu ,

From a [quick search](https://support.contrastsecurity.com/hc/en-us/articles/360025177492-Invalid-ELF-Header) and from #55 , this seems to be due to compiling and running modules across different OS-es.
