### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LiXiang0021** [alexandrosstergiou/SoftPool#55]
Thanks your great work!
Errors occur when i make install, error report like this 

ImportError: /home/envs/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: invalid ELF header.

And, i used python3.9 pytorch 1.12 with cuda 11.3.

**Comment by LiXiang0021** [comment]
Oh, I have solved this problem by using a lower PyTorch version 1.10.

**Comment by alexandrosstergiou** [comment]
Great, I'll close the issue then.
