### ISSUE TITLE
softpool_cuda

### ISSUE THREAD

**Issue by gxxdd** [alexandrosstergiou/SoftPool#59]
Hello, thank you very much for your work. Due to some reasons, I am unable to download softpool_cuda. Could you please provide a separate download link for him? Thank you very much.

**Comment by alexandrosstergiou** [comment]
Hi @gxxdd . Part of the repository includes native cuda code for faster computations. There is no separate `softpool_cuda` package. It is created after running `make install` based on your system's NVCC/CUDA version. 

If you can't build the repo use the pytorch-native implementations (see [these lines](https://github.com/alexandrosstergiou/SoftPool/blob/e11dee7e96ecad895cf871c8cbf220f7908462ed/pytorch/SoftPool/idea.py#L201-L208))
